### ISSUE TITLE
NoSuchMethodError: sun.java2d.marlin.MarlinProperties.isDoClip()Z

### ISSUE THREAD

**Issue by gitdode** [bourgesl/marlin-renderer#44]
I have set up:

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```
with https://github.com/bourgesl/marlin-renderer/releases/tag/v0_9_4_5 like this:

```
JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/a:/opt/marlin/marlin-0.9.4.5-Unsafe.jar"
JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/a:/opt/marlin/marlin-0.9.4.5-Unsafe-sun-java2d.jar"
JAVA_OPTS="$JAVA_OPTS -Dsun.java2d.renderer=sun.java2d.marlin.DMarlinRenderingEngine"
```
and I get:

```
java.util.ServiceConfigurationError: sun.java2d.pipe.RenderingEngine: Provider sun.java2d.marlin.DMarlinRenderingEngine could not be instantiated
[...]
Caused by: java.lang.NoSuchMethodError: sun.java2d.marlin.MarlinProperties.isDoClip()Z
  at sun.java2d.marlin.DMarlinRenderingEngine.<clinit>(DMarlinRenderingEngine.java:56)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at java.lang.Class.newInstance(Class.java:442)
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
  ... 47 more
```
It works fine with for example 0.9.4.1

Did I miss something or is this actually an issue?

**Comment by bourgesl** [comment]
Hi,

Yes it changed as the classes are now in sun.java2d package, you need to
prepend (not append) marlin jar into the boot classpath.

See https://github.com/bourgesl/marlin-renderer/wiki/How-to-use#jdk-8-0945

Laurent

Le mar. 14 déc. 2021 à 11:33, Torsten Römer ***@***.***> a
écrit :

**Comment by bourgesl** [comment]
Moreover, it is mandatory since OpenJDK 8 updates provide for 1 year Marlin
renderer 0.7... no yet up-to-date.

Enjoy FOSS & Marlin renderer,
Laurent

Le mar. 14 déc. 2021 à 12:19, Laurent Bourgès ***@***.***> a
écrit :

**Comment by gitdode** [comment]
Thanks a lot Laurent,

it works fine, sorry for overlooking the /p versus the /a.

Cheers,
Torsten

> Hi, Yes it changed as the classes are now in sun.java2d package, you need to prepend (not append) marlin jar into the boot classpath. See https://github.com/bourgesl/marlin-renderer/wiki/How-to-use#jdk-8-0945
